name: wt_action_button
description: Define and manage actions within an application.
publish_to: 'none'
version: 0.0.2
homepage: https://github.com/tmcmaster/wt_action_button

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  riverpod: ^2.0.2
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.0.2
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: