name: wt_action_button
description: Define and manage actions within an application.
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/tmcmaster/wt_action_button

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger:
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

dependency_overrides:
  wt_logging:
    path: ../wt_logging