name: wt_actions_examples
description: This is a project for managing user triggered actions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_riverpod:
  font_awesome_flutter:
  wt_action_button:
    path: ..
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



























