name: wt_actions_examples
description: This is a project for managing user triggered actions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  coverage:
    generate: ./bin/generate_coverage.sh
    view: open coverage/html/index.html

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  wt_action_button:
    path: ..
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



























